### ISSUE TITLE
Change of morfeo.useTheme method name

### ISSUE THREAD

**Issue by mauroerta** [morfeojs/morfeo#142]
## The problem

I think that the `useTheme` method of `morfeo` can result ambiguous in a react environment, for example:

```typescript
const { useTheme } = morfeo;
// Can be confused with the hook `useTheme` of `@morfeo/hook`
useTheme('dark');
```
Also other problems can occur, for example:

```typescript
const { useTheme } = morfeo;
if (condition) {
  // this is completely legal, since `useTheme` is not a hook (in this case) so we are not calling
  // an hook conditionally. 
  // but the linter will complain since it will not understand that useTheme is not a hook.
  useTheme('dark');
}
```
## Solution

Instead of `useTheme` we can rename this method `setCurrent`, for me it makes sense even because we have a similar method called `getCurrent` that retrieves the name of the current theme:

```typescript
const { setCurrent } = morfeo;
// No ambiguity with `useTheme`
setCurrent('dark');
```

Also. since all the other methods related to the theme contains the suffix `theme`, we can this about rename not only `useTheme` but also `getCurrent` in this way:

- `morfeo.useTheme` will become `morfeo.setCurrentTheme`
- `morfeo.getCurrent` will become `morfeo.getCurrentTheme`

**Comment by andreaSimonePorceddu** [comment]
I totally agree.
